config/routes.rb
GeekCorps::Application.routes.draw do

  get 'privacy' => 'pages#privacy'
  get 'about' => 'pages#about'
  get 'api' => 'pages#api'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact'
  get 'terms' => 'pages#terms'
  get 'admin' => 'pages#admins'

  resources :skills  
  match 'apps' => 'apps#index', :as => 'apps'

  root :to => "people#index"

  resources :authentications

  resources :people do
    collection do
      get 'list', :action => :list
    end
    member do
      get 'claim'
      get 'photo'
    end
  end
  get '/people/tag/:tag(.:format)' => 'people#tag', :as => 'people_tagged', :constraints => {:tag => /.*/}

  resources :users, :only => [:show, :index, :destroy] do
    member do
      post 'adminify'
    end
  end
  get '/welcome' => 'users#welcome', :as => 'welcome_users'
  get '/home' => 'users#home', :as => 'home_users'

  resources :user_sessions, :only => [:new, :create], :controller => 'users/sessions'

  devise_for :users do
    get "/sign_out" => "devise/sessions#destroy"
    get "/sign_in" => "users/sessions#new"
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/auto' => 'authentications#auto'
  match '/auth/failure' => 'authentications#auth_failure'

  resources :teams do
    resources :members
  end

  put 'team_members/:id' => 'team_members#update', :as => 'team_member'

  post "comments/create"

  controller :teams do
    get '/:team_name' => :show
    get '/:team_name/people' => 'teams#people', :as => 'team_people'
    get '/:team_name/guide/' => 'milestones#index', :as => 'team_guide'
  end



end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  extend ActiveSupport::Memoizable

  belongs_to :user
  serialize :info

  before_validation(:initialize_user_if_absent, :on => :create)
  after_save :attach_matching_person_to_user

  validates_presence_of :user

  scope :via, lambda{|provider| where(:provider => provider)}
  scope :searchable, where("provider = 'twitter' OR provider = 'facebook' OR provider = 'linked_in'")

  SETTINGS['providers'].each do |provider|
    scope "via_#{provider.to_sym}", where("provider = ?", provider)
  end

  PROVIDER_OPTIONS = SETTINGS['providers'].map{|provider|
                            [OmniAuth::Utils.camelize(provider), provider]
                          }

  def api_client
    APIClient.for(self)
  end
  memoize :api_client

  def to_person
    if self.api_client
      if self.uid.present?
        api_client.get(self.uid)
      else
        Person.new
      end
    else
      Person.new(
          :name => self.info[:name],
          :location => self.info[:location],
          :bio => self.info[:description],
          :photo_import_url => self.info[:image],
          :url => self.info[:urls].try(:values).try(:first)
        )
    end
  end

  #--[ Updating information at auth-time ]-------------------------------------

  def update_from_omniauth(omniauth)
    extract_credentials_from_omniauth(omniauth)
    extract_info_from_omniauth(omniauth)
  end

  def extract_credentials_from_omniauth(omniauth)
    if omniauth.has_key?('credentials')
      self.access_token = omniauth['credentials']['token']
      self.access_token_secret = omniauth['credentials']['secret']
    end
  end

  # We only want to retain certain user info from omniauth responses, depending on the provider.
  def extract_info_from_omniauth(omniauth)
    if omniauth.has_key?('extra') && omniauth['extra'].has_key?('user_hash')
      self.info = omniauth['user_info'].merge(omniauth['extra']['user_hash']).symbolize_keys
    else
      self.info = omniauth['user_info'].symbolize_keys
    end
  end

  #--[ Building Authentications from OmniAuth responses ]----------------------

  def self.new_from_omniauth(omniauth, options={})
    new_user = options.delete(:new_user)
    options.reverse_merge!(:provider => omniauth['provider'], :uid => omniauth['uid'])

    auth = self.new(options)
    auth.update_from_omniauth(omniauth)

    auth.build_user(new_user) if new_user.present?

    auth
  end

  def self.create_from_omniauth(omniauth, options={})
    auth = self.new_from_omniauth(omniauth, options)
    auth if auth.save
  end

  def self.create_from_omniauth!(omniauth, options={})
    auth = self.new_from_omniauth(omniauth, options)
    auth if auth.save!
  end

  def initialize_user_if_absent
    self.build_user unless self.user.present?
  end

  def matching_person
    @matching_person ||= Person.where(:imported_from_provider => self.provider,
                                      :imported_from_id => self.uid).first
  end

  def attach_matching_person_to_user
    if self.user && self.user.person.nil? && matching_person.present?
      matching_person.update_attribute(:user_id, self.user_id)
    end
  end
end



# == Schema Information
#
# Table name: authentications
#
#  id                  :integer(4)      not null, primary key
#  user_id             :integer(4)
#  provider            :string(255)
#  uid                 :string(255)
#  access_token        :string(255)
#  access_token_secret :string(255)
#  info                :text
#  created_at          :datetime
#  updated_at          :datetime
#

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  class SessionRequired < Exception; end

  before_filter :authenticate_user!, :only => [:destroy]
  skip_before_filter :verify_authenticity_token, :only => :create

  def index
    @authentications = current_user.authentications.all
  end

  def auth_failure
    # just render the failure view
  end

  def create
    omniauth = request.env["omniauth.auth"]

    if auth = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'].to_s)
      # Existing user, existing authentication, login!
      auth.update_from_omniauth(omniauth)
      auth.save
      sign_in(auth.user)
    elsif current_user
      # Logged in user => give them a new authentication
      Authentication.create_from_omniauth!(omniauth, :user => current_user)
      flash[:success] = "Your #{OmniAuth::Utils.camelize(omniauth['provider'])} account has been added."
    else
      # Entirely new user
      if session[:login_email].blank?
        flash[:error] = "It looks like you might have cookies disabled. Please re-enable cookies and try again."
      elsif User.find_by_email(session[:login_email])
        flash[:error] = "A user already exists for #{session[:login_email]}, but you're using a different login method than we've seen for them. Please try again with with the 'choose automatically' option selected."
      else
        auth = Authentication.create_from_omniauth!(omniauth, :new_user => {:email => session[:login_email]})
        flash[:notice] = "Signed in successfully."
      end

      session[:login_email] = nil
      if auth.present?
        sign_in(auth.user)
      else
      end
    end
    redirect_to :back
  end

  def destroy
    if current_user.admin?
      @authentication = Authentication.find(params[:id])
    else
      @authentication = current_user.authentications.find(params[:id])
    end
    @authentication.destroy
    flash[:success] = "Your #{OmniAuth::Utils.camelize(@authentication.provider)} account has been removed."
    redirect_to welcome_users_path
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
  def provider_icon(provider, size=32)
    path = File.join('authbuttons',"#{provider}_#{size}.png")
    provider_name = OmniAuth::Utils.camelize(provider)

    if File.exists?(Rails.root.join('public', 'assets', path))
      image_tag(path, :alt => provider_name)
    else
      provider_name
    end
  end

  def auth_label(authentication)
    if authentication.info[:nickname].present?
      name = authentication.info[:nickname]
    else
      name = authentication.info[:name]
    end
     "#{name} on #{provider_name(authentication.provider)}"
  end
end

app/views/authentications/_add_auth_form.html.erb
<div class="sidebar_box sb_container">
    <div class="sidebar_box_title">Your Social Networks</div>
    <div class="sidebar_box_content ">
      <span>Click the + or - sign to add/remove an account<span>
      <ul class="auth_providers">
        <% SETTINGS['providers'].each do |provider| %>
          <li><%= link_to OmniAuth::Utils.camelize(provider), "/auth/#{provider}", :class => provider %>
          <% if auth = current_user.authentications.via(provider).first %>
            <%= link_to '&nbsp;'.html_safe, auth, :class => 'auth-delete', :method => :delete %>
          <% else %>
            <%= link_to '&nbsp;'.html_safe, "/auth/#{provider}", :class => 'auth-add' %>
          <% end %>
          </li>
        <% end %>
      </ul>
      <div class="clear"></div>
    </div>
</div>

app/views/authentications/_list.html.erb
<ul class="authentications" >
  <% list.each do |authentication| %>
    <li class="<%= authentication.provider] %>" id="<%= "#{authentication.provider}_#{authentication.uid}" %>" >
      <%= provider_icon(authentication.provider) %>
      <%= auth_label(authentication) %>
      <% if list.size > 1 %>
        <%= link_to "Remove", authentication_path(authentication), :confirm => 'Are you sure?', :method => :delete, :class => 'delete' %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/authentications/_login_form.html.erb
<div class="sign_in_form">
  <h1> Sign In </h1>  
  <%= form_for SignInData.new, :url => user_sessions_path do |f| %>
    <p><%= f.label :email, "Email Address" %><br>
    <%= f.text_field :email, :size => nil, :autocorrect => "off", :autocapitalize => "off" %></p>
    <p><%= f.label :provider, "Social Network Provider" %><br>
    <%= select :sign_in_data, :provider, Authentication::PROVIDER_OPTIONS %><br>
    <span>Note, we only use social network authentication mechanisms such as Facebook connect.</span>
    </p>
    <%= f.submit "Sign in!", :id => "guide_submit" %>
  <% end %>
</div>

app/views/authentications/_provider_list.html.erb
<ul class="auth_providers">
  <% SETTINGS['providers'].each do |provider| %>
    <li><%= link_to OmniAuth::Utils.camelize(provider), "/auth/#{provider}", :class => provider %></li>
  <% end %>
</ul>

app/views/authentications/_signin_and_join_team.html.haml
%h1 Join This Team
= form_for SignInData.new, :url => user_sessions_path do |f|

  .fieldset
    .clearfix
      = f.label :email, "Email Address"
      .input
        = f.text_field :email, :size => nil, :autocorrect => "off", :autocapitalize => "off"
    .clearfix
      = f.label :provider, "Social Network Provider"
      = hidden_field_tag :join_team_id, @team.id
      .input
        = select :sign_in_data, :provider, Authentication::PROVIDER_OPTIONS

  = f.submit "Sign in!", :id => "guide_submit", :class => "btn primary"

app/views/authentications/auth_failure.html.erb
<h1> Ack! Something went wrong!</h1>
<p> We received an error of some kind back from your login provider. You can try again with the same login provider or choose another service.</p>
<h2> Please pick a login provider to continue: </h2>
<%= render :partial => 'provider_list' %>

app/views/authentications/auto.html.erb
<h1> Eep! We couldn't find a way to log you in!<h1>
<p> We tried to automatically pick a login provider for you based on your email address, but didn't find one.</p>
<h2> Please pick a login provider to continue: </h2>
<%= render :partial => 'provider_list' %>

app/views/authentications/index.html.erb
<h1> Authentications </h1>
<%= link_to 'New Authentication', new_authentication_path %>

<table>
  <tr>
    <th></th>
    <th> Provider </th>
    <th> Name </th>
    <th> Account </th>
    <th> Actions </th>
  </tr>
  <% for authentication in @authentications %>
    <tr>
      <td>
        <% if authentication.info[:image] %>
          <img src=<%= authentication.info[:image] %> width=48 height=48 />
        <% end %>
      </td>
      <td><%= provider_icon(authentication.provider) %></td>
      <td><%= authentication.info[:name] %></td>
      <td><%= authentication.info[:nickname] %></td>
      <td>
        <% if @authentications.size > 1 %>
          <%= link_to "Remove", authentication_path(authentication), :confirm => 'Are you sure?', :method => :delete %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>