config/routes.rb
GeekCorps::Application.routes.draw do

  get 'privacy' => 'pages#privacy'
  get 'about' => 'pages#about'
  get 'api' => 'pages#api'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact'
  get 'terms' => 'pages#terms'
  get 'admin' => 'pages#admins'

  resources :skills  
  match 'apps' => 'apps#index', :as => 'apps'

  root :to => "people#index"

  resources :authentications

  resources :people do
    collection do
      get 'list', :action => :list
    end
    member do
      get 'claim'
      get 'photo'
    end
  end
  get '/people/tag/:tag(.:format)' => 'people#tag', :as => 'people_tagged', :constraints => {:tag => /.*/}

  resources :users, :only => [:show, :index, :destroy] do
    member do
      post 'adminify'
    end
  end
  get '/welcome' => 'users#welcome', :as => 'welcome_users'
  get '/home' => 'users#home', :as => 'home_users'

  resources :user_sessions, :only => [:new, :create], :controller => 'users/sessions'

  devise_for :users do
    get "/sign_out" => "devise/sessions#destroy"
    get "/sign_in" => "users/sessions#new"
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/auto' => 'authentications#auto'
  match '/auth/failure' => 'authentications#auth_failure'

  resources :teams do
    resources :members
  end

  put 'team_members/:id' => 'team_members#update', :as => 'team_member'

  post "comments/create"

  controller :teams do
    get '/:team_name' => :show
    get '/:team_name/people' => 'teams#people', :as => 'team_people'
    get '/:team_name/guide/' => 'milestones#index', :as => 'team_guide'
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_protected :admin
  has_one :person
  has_many :team_members
  has_many :teams, :through => :team_members, :source => :team
  has_many :comments

  scope :admins, joins(:team_members).where(:team_members => {:admin => true})

  has_many :authentications, :dependent => :destroy do
    def info_get(key)
      info_with_key = self.map(&:info).compact.detect{|info| info[key].present? }
      return info_with_key[key] if info_with_key.present?
    end
  end

  devise :rememberable, :trackable

  def avatar_url
    if self.person.present?
      self.person.photo.url(:thumb)
    elsif self.authentications.present?
      (self.authentications.info_get(:image) || '/assets/geekcorpsavatar1.png')
    else
      '/assets/geekcorpsavatar1.png'
    end
  end

  def name
    self.person.try(:name) || self.authentications.info_get(:name) || "User #{self.id}"
  end

  def label_for_admin
    "#{self.id}: #{self.name} #{self.person.present? ? '*' : ''}"
  end

  def default_authentication
    self.authentications.first
  end

  def has_auth_from?(provider)
    self.authentications.via(provider).present?
  end

  def is_admin_for
    self.team_members.where(:admin => true)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  def new
    @signin_data = SignInData.new
  end

  def create
    @signin_data = SignInData.new(params[:sign_in_data])
    render(:action => :new) and return unless @signin_data.valid?
    if params[:join_team_id]
      session[:join_team_id] = params[:join_team_id]
    end
    session[:login_email] = @signin_data.email
    redirect_to "/auth/#{@signin_data.provider}"
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  before_filter :authenticate_user!, :only => [:welcome, :home]
  before_filter :require_admin!, :except => [:show, :home, :welcome]

  def show
    if resource.person
      redirect_to person_path(resource.person)
    else
      if current_user && current_user.admin?
        redirect_to users_path(:anchor => "user_#{resource.id}")
      else
        raise ActiveRecord::RecordNotFound
      end
    end
  end

  def home
    redirect_to :action => :welcome and return unless current_user.person.try(:reviewed)
  end

  def welcome
    redirect_to :action => :home and return if current_user.person.try(:reviewed)

    @name = current_user.name || params[:name]
    @person = current_user.person || current_user.authentications.first.to_person || Person.new

    if @person.new_record?
      if @name.present?
        @possible_duplicates = Person.unclaimed.where(:name => @name).all

        name_parts = @name.split(' ')
        name_part_query = (["name LIKE ?"] * name_parts.size).join(' or ')
        @possible_duplicates += Person.unclaimed.where(name_part_query, *name_parts.map{|p| "%#{p}%"}).take(10)

        @possible_duplicates.uniq!
      end
    end
  end

  def index
    @users = User.includes(:authentications, :person).all
  end

  def adminify
    @user = User.where(:id => params[:id]).first  
    @user.admin = !(@user.admin)
    @user.save
    
    flash[:notice] = @user.admin? ? "Adminified User" : "UnAdminified User"
    redirect_to :back
  end
end

app/views/users/home.html.erb
<% content_for(:section_header) do %>
  <div class="section_header events">
    <h1> Hey there! </h1>
  </div>
<% end %>

<div id="user_home">
  <div id="profile">
    <h2> What would you like to do? </h2>
    <ul>
      <li><%= link_to "View your profile", person_path(current_person) %></li>
      <li><%= link_to "Edit your profile", edit_person_path(current_person) %></li>
      <li><%= link_to "Add a friend to the directory", new_person_path %></li>
    </ul>
  </div>
  <div id="authentications">
    <h2> Linked Accounts </h2>
    <%= semantic_form_for(SignInData.new(:email => current_user.email), :url => user_sessions_path) do |f| %>
      <%= f.inputs do %>
        <%= f.input :email, :as => :hidden %>
        <%= f.input :provider, :collection => Authentication::PROVIDER_OPTIONS, :prompt => 'Pick a service…', :label => 'Add an account' %>
      <% end %>
      <%= f.buttons do %>
        <%= f.commit_button "Add it!" %>
      <% end %>
    <% end %>

    <%= render :partial => 'authentications/list', :object => current_user.authentications %>
  </div>
</div>

app/views/users/index.html.erb
<div id="users_admin">
  <h1> Users </h1>
  <ul>
    <% @users.each do |user| %>
      <li id="user_<%= user.id %>" class="<%= user.admin? ? 'admin' : nil %>">
        <% if user.admin? %>
          <strong> Admin </strong>
        <% end %>
        <%= "User #{user.id}: #{user.name} -" %>
        <%= mail_to user.email %>
        <%= link_to "Delete", user_path(user), :confirm => 'Are you sure?', :method => :delete, :class => 'delete' %>
        <%= link_to ((user.admin? ? 'Un-' : '') + 'adminify').capitalize, adminify_user_path(user), :method => :post, :class => 'make_admin' %>
        <%= image_tag(normalize_url(user.avatar_url), :size => '30x30', :align => 'right') if user.avatar_url %>
        <ul>
          <% if user.person.present? %>
            <li id="person_<%= user.person.id %>">
              <%= "Person #{user.person.id}:" %>
              <%= link_to user.person.name, person_path(user.person) %>
            </li>
          <% user.authentications.each do |auth| %>
            <li id="authentication_<%= auth.id %>">
              <%= "Authentication #{auth.id}: #{auth.info[:name]}" %>
              <%= "(#{auth.info[:nickname]})" if auth.info[:nickname] %>
              <%= "via #{provider_name(auth.provider)}" %>
              <%= link_to "Delete", authentication_path(auth), :confirm => 'Are you sure?', :method => :delete, :class => 'delete' %>
              <% if auth.matching_person && auth.matching_person != user.person %>
                <ul>
                  <li>
                    <%= "Person #{user.id}:" %>
                    <%= link_to auth.matching_person.name, person_path(auth.matching_person) %>
                  </li>
                </ul>
              <% end %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/welcome.html.erb
<div id="content">
  <div id="title-main">
    <% if !@person.new_record? %>
      <%= render "people/person_header"%>
    <% else %>
      <h1 class="welcome">Welcome to the Geek Corps!</h1>    
    <% end %>
  </div>
  <div id="main-bar">
    <div class="project-text">
      <h1>Edit Your Information</h1>
      <% if @person.new_record? %>
        <p><%= "We imported as much info as we could from your #{provider_name(current_user.authentications.first.provider)} account. Look it over and hit the big button to get started."%></p>
      <% else %>      
        <p><%= "You were already in the directory! Please review your details and let us know they're right." %>
      <%end%>
    </div>
    <% if @person.new_record?%>
      <%= render :partial => 'people/new_form' %>
    <% else%>
      <%= render :partial => 'people/form' %>
    <% end %>
    </div>
  </div>
  <div id="side-bar">
    <%= render :partial => 'authentications/add_auth_form' %>
    <%= render :partial => 'people/person_edit_image' %>    
  </div>
</div>