config/routes.rb
GeekCorps::Application.routes.draw do

  get 'privacy' => 'pages#privacy'
  get 'about' => 'pages#about'
  get 'api' => 'pages#api'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact'
  get 'terms' => 'pages#terms'
  get 'admin' => 'pages#admins'

  resources :skills  
  match 'apps' => 'apps#index', :as => 'apps'

  root :to => "people#index"

  resources :authentications

  resources :people do
    collection do
      get 'list', :action => :list
    end
    member do
      get 'claim'
      get 'photo'
    end
  end
  get '/people/tag/:tag(.:format)' => 'people#tag', :as => 'people_tagged', :constraints => {:tag => /.*/}

  resources :users, :only => [:show, :index, :destroy] do
    member do
      post 'adminify'
    end
  end
  get '/welcome' => 'users#welcome', :as => 'welcome_users'
  get '/home' => 'users#home', :as => 'home_users'

  resources :user_sessions, :only => [:new, :create], :controller => 'users/sessions'

  devise_for :users do
    get "/sign_out" => "devise/sessions#destroy"
    get "/sign_in" => "users/sessions#new"
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/auto' => 'authentications#auto'
  match '/auth/failure' => 'authentications#auth_failure'

  resources :teams do
    resources :members
  end

  put 'team_members/:id' => 'team_members#update', :as => 'team_member'

  post "comments/create"

  controller :teams do
    get '/:team_name' => :show
    get '/:team_name/people' => 'teams#people', :as => 'team_people'
    get '/:team_name/guide/' => 'milestones#index', :as => 'team_guide'
  end



end

app/views/shared/_comment.html.erb
<% form_for :comment, :url => comments_create_path do |f| -%>
<div id="comment-subform">
  <%= f.text_area :text, :rows => nil %>
  <%= f.hidden_field :team_id, :value => @team.id %>
  <%= f.hidden_field :commentable_type, :value => comment.class %>
  <%= f.hidden_field :commentable_id, :value => comment.id %>
  <div id="mainselection">
    <%= f.select :flag, [['Chatter', 1]] %>
  </div>
  <%= f.submit "Post" %>
  <div style="clear:both; height:0;"></div>
</div>
<% end -%>

app/views/shared/_comment_list.html.erb
<div id="feed-wrapper">
  <h1>Comments</h1>
  <div id="activity-feed">
  <% comment.comments.order("created_at DESC").each do |feed| %>
    <div class="feed-item">
      <%= activity_image(feed)%>
      <span class="comment-body"><%=feed.text%></span>
      <span class="comment-stamp"><%= activity_type("Comment")%>, <%= time_ago_in_words(feed.created_at)%><span>
    </div>
  <% end %>
  <%= render "shared/comment", :comment => comment %>
  </div>
</div>

app/views/shared/_footer.html.haml
%footer.footer
  .container
    %ul
      %li
        = link_to 'About', about_path
      %li
        = link_to 'Blog', blog_path
      %li
        = link_to 'API', api_path
      %li
        = link_to 'Contact', contact_path
      %li
        = link_to 'Terms', terms_path
      %li
        = link_to 'Privacy', privacy_path

    %p
      Powered by
      = link_to 'Citizenry', 'http://github.com/reidab/citizenry/'

    %p
      Created as Open Source by <a href="#">Code for America</a>
      %q For a more transparent, efficient, and participatory future.
      <a href="http://codeforamerica.org" id="cfa-logo"><img src="assets/cfa-full-logo.png"></a>

app/views/shared/_header.html.haml
.topbar-wrapper{:style => "z-index: 5;"}
  .topbar{"data-dropdown" => "dropdown"}
    .topbar-inner
      .container
        %h3
          =link_to 'Civic Corps', root_path
        %ul.nav
          %li
            = link_to 'Find People', people_path
          %li
            = link_to 'Join a Team', teams_path
          - if current_user and current_user.admin?
            %li
              = link_to 'Admin', admin_path
        - if current_user
          %ul.nav.secondary-nav
            %li.dropdown
              = link_to current_user.name, '#', :class => "dropdown-toggle"
              %ul.dropdown-menu
                %li
                  = link_to "Settings", home_users_path, :id => 'user-setting'
                %li.divider
                %li
                  = link_to 'Sign Out', sign_out_path, :id => 'sign-out'
        - else
          %ul.nav.secondary.nav
            %li
              = link_to 'Sign In', sign_in_path

app/views/shared/_list.html.erb
<ul id="front-list" class="main-list-type">
  <%= render :partial => 'shared/list_item', :collection => list %>
</ul>
<script>
  $('#front-list').isotope();
</script>

app/views/shared/_list_item.html.erb
<li class="front-box">
  <h3><%= link_to list_item.name, polymorphic_path(list_item) %></h3>
  <%= image_tag list_item.photo.url %>
</li>

app/views/shared/_list_pagination.html.erb
<% if list_pagination.respond_to?(:total_pages) && list_pagination.total_pages > 1 %>
  <div class="pagination">
    <%= will_paginate list_pagination %>
    <%= link_to "Show all", params.merge('page' => 'all'), :class => 'all' %>
  </div>
<% end %>

app/views/shared/_search.html.erb
<%= form_for @search, :url => polymorphic_path(resource), :html => {:method => :get} do |f| %>
  <%= f.text_field :name_contains, :id => 'main-search' %>
  <%= f.select :roles_id_equals, Role.all.map {|r| [r.name, r.id] }, {:include_blank => true} %>
  <%= f.select :skills_id_equals, Skill.all.map {|s| [s.name, s.id] }, {:include_blank => true} %>
  <%= f.select :languages_id_equals, Language.all.map {|l| [l.name, l.id] }, {:include_blank => true} %>
  <input id="main-submit" type="image" alt="Search" value="Search" src="/assets/binocular.png" />
<% end %>

app/views/shared/_tag_list.html.erb
 <a href="/people?skill=<%=skill%>"><%=skill%></a>

app/views/shared/_team_header.html.haml
%h1
  =link_to @team.name.titleize, @team.to_url
- if !@team.team_members.where(:admin => true).blank?
  %h2
    Organized by
    =raw @team.team_members.where(:admin => true).map { |organizer| link_to organizer.user.person.name, organizer.user.person }.to_sentence